return function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;
    var locals_for_with = (locals || {});
    
    (function (data) {
      ;pug_debug_line = 1;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003C!DOCTYPE html\u003E";
;pug_debug_line = 2;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Chtml v=\"1.0.6\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_mixins["imgPlus"] = pug_interp = function(src){
var block = (this && this.block), attributes = (this && this.attributes) || {};
;pug_debug_line = 4;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
src = "https://resource.smartreviewstips.com/" + src
;pug_debug_line = 5;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cimg" + (" class=\"cs-lazy\""+pug.attr("data-load", src, true, true)+" alt=\"\"") + "\u003E";
;pug_debug_line = 6;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"loading-img\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"loading-inner\"\u003E";
;pug_debug_line = 8;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"dots-container\"\u003E";
;pug_debug_line = 9;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 10;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 11;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 12;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"dot\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 13;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"dot\"\u003E";
;pug_debug_line = 13;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + " \u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
};
;pug_debug_line = 14;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_mixins["searchComp"] = pug_interp = function(){
var block = (this && this.block), attributes = (this && this.attributes) || {};
;pug_debug_line = 15;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"searchComp\"\u003E";
;pug_debug_line = 16;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002Flogo3.svg\" alt=\"\"\u003E";
;pug_debug_line = 17;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 17;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "Explore, rate and share together! \u003C\u002Fp\u003E";
;pug_debug_line = 18;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 18;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "We provide reliable reviews to help consumers choose smarter.\u003C\u002Fp\u003E";
;pug_debug_line = 19;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"searchComp-input box-shadow-20\"\u003E";
;pug_debug_line = 20;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cinput class=\"searchInputComp\" type=\"search\" placeholder=\"Search for any reviews\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv\u003E";
;pug_debug_line = 22;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002Fsearch.svg\" alt=\"\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
};
;pug_debug_line = 23;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Chead\u003E";
;pug_debug_line = 24;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
;pug_debug_line = 3;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003C\u002Fhead\u003E";
;pug_debug_line = 25;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cbody\u003E";
;pug_debug_line = 26;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
pug_html = pug_html + "\u003Cdiv class=\"content-body\"\u003E";
;pug_debug_line = 27;pug_debug_filename = "d:\\Web\\pugFrame\\template\\common\\base.pug";
;pug_debug_line = 5;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"index\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"banner1\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"banner1-left\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 8;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ch1\u003E";
;pug_debug_line = 8;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "Smart Decisions ";
;pug_debug_line = 9;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 9;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 10;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 10;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "Begin with \u003C\u002Fspan\u003E\u003C\u002Fp\u003E";
;pug_debug_line = 11;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 11;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 12;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"imgLowerLine\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "Smart \u003C\u002Fspan\u003E";
;pug_debug_line = 13;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 13;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "Reviews!\u003C\u002Fspan\u003E\u003C\u002Fp\u003E\u003C\u002Fh1\u003E";
;pug_debug_line = 14;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"desc-text\"\u003E";
;pug_debug_line = 14;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\"Explore a world of perspectives and insights on our review platform, where diverse evaluations across all realms converge to enlighten and empower your decisions.\"\u003C\u002Fp\u003E";
;pug_debug_line = 15;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"banner1-search box-shadow-20\"\u003E";
;pug_debug_line = 16;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv\u003E";
;pug_debug_line = 16;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 17;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cinput class=\"searchInput\" type=\"search\" placeholder=\"Search for any reviews\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg class=\"icon-18\" src=\"\u002Fstatic\u002Fsearch.svg\" alt=\"\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 19;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"but-text\"\u003E";
;pug_debug_line = 19;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " \u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 20;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"banner1-right\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 22;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"banner2\"\u003E";
;pug_debug_line = 23;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"banner2-left\"\u003E";
;pug_debug_line = 24;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"cat-text\"\u003E";
;pug_debug_line = 24;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.top.posts[0].cat) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 25;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"title\"\u003E";
;pug_debug_line = 25;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.top.posts[0].title) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 26;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"desc-text three-lines\"\u003E";
;pug_debug_line = 26;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.top.posts[0].quote.slice(0).slice(0,-1)) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 27;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ca" + (" style=\"margin-top:10px\""+pug.attr("href", `/detail/${data.top.posts[0].page_name}.html`, true, true)) + "\u003E";
;pug_debug_line = 27;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 28;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"title-2 ViewDetailsHover\"\u003E";
;pug_debug_line = 28;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "View Details\u003C\u002Fspan\u003E";
;pug_debug_line = 29;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg class=\"ViewDetailsHover icon-18\" src=\"\u002Fstatic\u002FGroup 297.svg\" alt=\"\"\u003E\u003C\u002Fa\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 30;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"banner2-right\"\u003E";
;pug_debug_line = 30;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 31;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"left\"\u003E";
;pug_debug_line = 31;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 32;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"box-shadow-40\"\u003E";
;pug_debug_line = 32;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 33;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FAutomotive Products.svg\" alt=\"\"\u003E";
;pug_debug_line = 34;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"title-2\"\u003E";
;pug_debug_line = 34;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 34;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.cats[0]) ? "" : pug_interp));
;pug_debug_line = 34;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " \u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 35;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"box-shadow-40\"\u003E";
;pug_debug_line = 35;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 36;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FConsumer Electronics.svg\" alt=\"\"\u003E";
;pug_debug_line = 37;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"title-2\"\u003E";
;pug_debug_line = 37;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 37;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.cats[2]) ? "" : pug_interp));
;pug_debug_line = 37;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " \u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 38;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"right\"\u003E";
;pug_debug_line = 38;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "      ";
;pug_debug_line = 39;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"box-shadow-40\"\u003E";
;pug_debug_line = 39;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 40;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FHome Appliances.svg\" alt=\"\"\u003E";
;pug_debug_line = 41;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"title-2\"\u003E";
;pug_debug_line = 41;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 41;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.cats[1]) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 42;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"box-shadow-40\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 43;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FHousehold Goods.svg\" alt=\"\"\u003E";
;pug_debug_line = 44;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"title-2\"\u003E";
;pug_debug_line = 44;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 44;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.cats[3]) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 45;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"BuyingGuides\"\u003E";
;pug_debug_line = 46;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ch1 class=\"title\"\u003E";
;pug_debug_line = 46;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.guides.title) ? "" : pug_interp));
;pug_debug_line = 47;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"chgBut\"\u003E";
;pug_debug_line = 48;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FArrowRightCircleFill.svg\" alt=\"\"\u003E";
;pug_debug_line = 49;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FArrowRightCircleFill.svg\" alt=\"\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fh1\u003E";
;pug_debug_line = 50;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"desc-text\"\u003E";
;pug_debug_line = 50;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.guides.content) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 51;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"scrollList\"\u003E";
;pug_debug_line = 52;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"imgList\"\u003E";
;pug_debug_line = 52;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 53;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
// iterate data.guides.posts
;(function(){
  var $$obj = data.guides.posts;
  if ('number' == typeof $$obj.length) {
      for (var pug_index0 = 0, $$l = $$obj.length; pug_index0 < $$l; pug_index0++) {
        var item = $$obj[pug_index0];
;pug_debug_line = 54;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ca" + (" class=\"imgItem\""+pug.attr("href", `/detail/${item.page_name}.html`, true, true)) + "\u003E";
;pug_debug_line = 55;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"top\"\u003E";
;pug_debug_line = 56;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_mixins["imgPlus"](item.imgs[0]);
;pug_debug_line = 57;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"info\"\u003E";
;pug_debug_line = 57;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 58;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"text-line\"\u003E";
;pug_debug_line = 58;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 58;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.title) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 59;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"viewDetailBut\"\u003E";
;pug_debug_line = 59;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 60;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 60;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "View Details\u003C\u002Fspan\u003E";
;pug_debug_line = 61;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg class=\"icon-18\" src=\"\u002Fstatic\u002FGroup 297.svg\" alt=\"\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 62;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"two-lines\"\u003E";
;pug_debug_line = 62;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 62;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.quote.slice(1).slice(0,-1)) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 63;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"bottom\"\u003E";
;pug_debug_line = 64;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 64;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.author) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 65;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 65;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 66;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg class=\"icon-21\" src=\"\u002Fstatic\u002Fstar.svg\" alt=\"\"\u003E";
;pug_debug_line = 67;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 67;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.rating) ? "" : pug_interp)) + "\u003C\u002Fspan\u003E\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fa\u003E";
      }
  } else {
    var $$l = 0;
    for (var pug_index0 in $$obj) {
      $$l++;
      var item = $$obj[pug_index0];
;pug_debug_line = 54;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ca" + (" class=\"imgItem\""+pug.attr("href", `/detail/${item.page_name}.html`, true, true)) + "\u003E";
;pug_debug_line = 55;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"top\"\u003E";
;pug_debug_line = 56;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_mixins["imgPlus"](item.imgs[0]);
;pug_debug_line = 57;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"info\"\u003E";
;pug_debug_line = 57;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 58;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"text-line\"\u003E";
;pug_debug_line = 58;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 58;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.title) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 59;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"viewDetailBut\"\u003E";
;pug_debug_line = 59;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 60;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 60;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "View Details\u003C\u002Fspan\u003E";
;pug_debug_line = 61;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg class=\"icon-18\" src=\"\u002Fstatic\u002FGroup 297.svg\" alt=\"\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 62;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"two-lines\"\u003E";
;pug_debug_line = 62;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 62;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.quote.slice(1).slice(0,-1)) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 63;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"bottom\"\u003E";
;pug_debug_line = 64;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 64;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.author) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 65;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 65;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 66;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg class=\"icon-21\" src=\"\u002Fstatic\u002Fstar.svg\" alt=\"\"\u003E";
;pug_debug_line = 67;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 67;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.rating) ? "" : pug_interp)) + "\u003C\u002Fspan\u003E\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fa\u003E";
    }
  }
}).call(this);

pug_html = pug_html + "\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 68;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"SamsungGalaxy\"\u003E";
;pug_debug_line = 69;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"left\"\u003E";
;pug_debug_line = 70;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FGroup 31.svg\" alt=\"smartreviews.com\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 71;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"right\"\u003E";
;pug_debug_line = 71;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 72;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"cat-text\"\u003E";
;pug_debug_line = 72;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.posts[0].cat) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 73;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"title\"\u003E";
;pug_debug_line = 73;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.posts[0].title) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 74;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"csList\"\u003E";
;pug_debug_line = 74;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 75;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 76;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FOpposite.svg\" alt=\"\"\u003E";
;pug_debug_line = 77;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"desc-text\"\u003E";
;pug_debug_line = 77;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_arr[0]) ? "" : pug_interp)) + "\u003C\u002Fspan\u003E\u003C\u002Fp\u003E";
;pug_debug_line = 78;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 79;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FOpposite.svg\" alt=\"\"\u003E";
;pug_debug_line = 80;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"desc-text\"\u003E";
;pug_debug_line = 80;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_arr[1]) ? "" : pug_interp)) + "\u003C\u002Fspan\u003E\u003C\u002Fp\u003E";
;pug_debug_line = 81;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 82;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FOpposite.svg\" alt=\"\"\u003E";
;pug_debug_line = 83;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"desc-text\"\u003E";
;pug_debug_line = 83;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_arr[2]) ? "" : pug_interp)) + "\u003C\u002Fspan\u003E\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 84;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"numInfo\"\u003E";
;pug_debug_line = 85;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"item\"\u003E";
;pug_debug_line = 86;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 86;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_obj[0].value) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 87;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 87;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_obj[0].key) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 88;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"item\"\u003E";
;pug_debug_line = 89;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 89;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_obj[1].value) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 90;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 90;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_obj[1].key) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 91;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"item\"\u003E";
;pug_debug_line = 92;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 92;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_obj[2].value) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 93;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 93;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.middle.content.str_obj[2].key) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 94;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ca" + (" class=\"toViewDetail\""+pug.attr("href", `${data.middle.posts[0].detail_url}`, true, true)) + "\u003E";
;pug_debug_line = 94;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 95;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"title-2 ViewDetailsHover\"\u003E";
;pug_debug_line = 95;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "View Details\u003C\u002Fspan\u003E";
;pug_debug_line = 96;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg class=\"ViewDetailsHover icon-18\" src=\"\u002Fstatic\u002FGroup 297.svg\" alt=\"\"\u003E\u003C\u002Fa\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 97;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"aboutMotive\"\u003E";
;pug_debug_line = 98;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"value\"\u003E";
;pug_debug_line = 98;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 99;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"left\"\u003E";
;pug_debug_line = 99;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 100;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"cat-text\"\u003E";
;pug_debug_line = 100;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.bottom.posts[0].cat) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 101;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"title\"\u003E";
;pug_debug_line = 101;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.bottom.title) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 102;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cp class=\"desc-text\"\u003E";
;pug_debug_line = 102;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = data.bottom.content) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 103;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cdiv class=\"right\"\u003E";
;pug_debug_line = 103;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + " ";
;pug_debug_line = 104;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
// iterate data.bottom.posts
;(function(){
  var $$obj = data.bottom.posts;
  if ('number' == typeof $$obj.length) {
      for (var pug_index1 = 0, $$l = $$obj.length; pug_index1 < $$l; pug_index1++) {
        var item = $$obj[pug_index1];
;pug_debug_line = 105;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ca" + (" class=\"item\""+pug.attr("href", item.detail_url, true, true)) + "\u003E";
;pug_debug_line = 106;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_mixins["imgPlus"](item.imgs[0]);
;pug_debug_line = 107;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"title-1 text-line\"\u003E";
;pug_debug_line = 107;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.title) ? "" : pug_interp)) + "\u003C\u002Fspan\u003E";
;pug_debug_line = 108;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FArrowRightCircleFill.svg\" alt=\"\"\u003E\u003C\u002Fa\u003E";
      }
  } else {
    var $$l = 0;
    for (var pug_index1 in $$obj) {
      $$l++;
      var item = $$obj[pug_index1];
;pug_debug_line = 105;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Ca" + (" class=\"item\""+pug.attr("href", item.detail_url, true, true)) + "\u003E";
;pug_debug_line = 106;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_mixins["imgPlus"](item.imgs[0]);
;pug_debug_line = 107;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cspan class=\"title-1 text-line\"\u003E";
;pug_debug_line = 107;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + (pug.escape(null == (pug_interp = item.title) ? "" : pug_interp)) + "\u003C\u002Fspan\u003E";
;pug_debug_line = 108;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_html = pug_html + "\u003Cimg src=\"\u002Fstatic\u002FArrowRightCircleFill.svg\" alt=\"\"\u003E\u003C\u002Fa\u003E";
    }
  }
}).call(this);

pug_html = pug_html + "\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 109;pug_debug_filename = "d:\\Web\\pugFrame\\template\\pages\\index.pug";
pug_mixins["searchComp"]();
pug_html = pug_html + "\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";
    }.call(this, "data" in locals_for_with ?
        locals_for_with.data :
        typeof data !== 'undefined' ? data : undefined));
    ;} catch (err) {pug.rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}